# ---------------------------------------------------------------------------------------------
# RLGrid: Grid world for analyzing maximization bias in RL using Q-learning and Double Q-learning
#
# config_rl_grid.yaml:
# > Configuration file
# ---------------------------------------------------------------------------------------------

# Training parameters
num_runs : 200          # Number of experiment runs
num_episodes : 3000     # Number of episodes per run

# Environment parameters
dyn_prob : 1.0          # Probability of reaching the desired state when taking a specific action

# Reward model parameters
prob_pos : 0.44         # Probability of receiving a positive reward
rew_pos_opt : 1         # Positive reward for the optimal pathway
rew_pos : 3             # General positive reward
rew_neg : -1            # Negative reward

# (Double) Q-learning hyperparameters
alpha : 0.05            # Learning rate
gamma : 0.8             # Discount factor
epsilon : 0.1           # Epsilon value for the epsilon-greedy policy